/**
 * Plazore product catalog — comprehensive marketplace categories
 * Keep web (web/src/lib/productCatalog.ts) and mobile (client/constants/productCatalog.ts) in sync
 */

export const PRODUCT_CATEGORIES: Record<string, string[]> = {
  Electronics: [
    'TVs & Home Theater',
    'Audio & Speakers',
    'Headphones & Earbuds',
    'Cameras & Photography',
    'Camera Lenses & Accessories',
    'Smart Home & IoT',
    'Wearables & Smartwatches',
    'Gaming Consoles',
    'Gaming Accessories',
    'Drones & RC',
    'Projectors',
    'Portable Electronics',
    'Other Electronics',
  ],
  'Phones & Accessories': [
    'Smartphones',
    'Feature Phones',
    'Phone Cases & Covers',
    'Screen Protectors',
    'Chargers & Cables',
    'Power Banks',
    'Wireless Chargers',
    'Earphones & Earbuds',
    'Phone Holders & Mounts',
    'SIM Cards & Memory Cards',
    'Phone Spare Parts',
    'Other',
  ],
  Computers: [
    'Laptops',
    'Desktops & All-in-Ones',
    'Tablets',
    'Monitors',
    'Computer Components',
    'CPUs & GPUs',
    'Motherboards',
    'RAM & Memory',
    'Storage (SSD/HDD)',
    'Keyboards & Mice',
    'Webcams & Microphones',
    'Printers & Scanners',
    'Networking & Routers',
    'Chargers & Adapters',
    'Laptop Spare Parts',
    'Software',
    'Other',
  ],
  Fashion: [
    "Men's Clothing",
    "Women's Clothing",
    'Unisex Clothing',
    'Kids Clothing',
    'Baby Clothing',
    "Men's Shoes",
    "Women's Shoes",
    'Unisex Shoes',
    'Kids & Baby Shoes',
    'Bags & Handbags',
    'Luggage & Travel',
    'Belts',
    'Hats & Caps',
    'Scarves & Gloves',
    'Underwear & Loungewear',
    'Socks',
    'Traditional & Cultural Wear',
    'Uniforms & Workwear',
    'Other Fashion',
  ],
  'Beauty & Personal Care': [
    'Skincare',
    'Makeup',
    'Haircare',
    'Hair Extensions & Wigs',
    'Fragrance & Perfume',
    'Bath & Body',
    'Oral Care',
    "Men's Grooming",
    'Beauty Tools & Appliances',
    'Nail Care',
    'Sun Care',
    'Other',
  ],
  'Home & Living': [
    'Home Decor',
    'Wall Art & Mirrors',
    'Bedding & Linens',
    'Bath',
    'Lighting & Lamps',
    'Storage & Organization',
    'Curtains & Blinds',
    'Rugs & Carpets',
    'Cushions & Throws',
    'Cleaning Supplies',
    'Home Fragrance',
    'Clocks',
    'Other',
  ],
  Furniture: [
    'Living Room Furniture',
    'Bedroom Furniture',
    'Dining Furniture',
    'Office & Study Furniture',
    'Outdoor & Garden Furniture',
    'Kids Furniture',
    'Storage Furniture',
    'Mattresses',
    'Sofas & Couches',
    'Tables & Desks',
    'Chairs & Seating',
    'Other',
  ],
  'Kitchen & Dining': [
    'Cookware',
    'Bakeware',
    'Small Kitchen Appliances',
    'Large Kitchen Appliances',
    'Tableware & Dinnerware',
    'Drinkware & Glassware',
    'Utensils & Gadgets',
    'Kitchen Storage & Containers',
    'Cutlery',
    'Water Filters & Dispensers',
    'Other',
  ],
  Groceries: [
    'Food Staples (Rice, Pasta, Grains)',
    'Fruits & Vegetables',
    'Meat & Poultry',
    'Seafood & Fish',
    'Dairy & Eggs',
    'Beverages',
    'Snacks & Confectionery',
    'Pantry & Spices',
    'Oils & Sauces',
    'Frozen Foods',
    'Bakery & Bread',
    'Organic & Specialty',
    'Baby Food',
    'Other',
  ],
  Health: [
    'Supplements & Vitamins',
    'Medical Devices',
    'First Aid & Wound Care',
    'Wellness & Fitness Nutrition',
    'Personal Health Monitors',
    'Mobility Aids',
    'Orthopedic Supports',
    'Sexual Wellness',
    'Prescription-Adjacent Care',
    'Other',
  ],
  'Sports & Outdoors': [
    'Fitness & Gym Equipment',
    'Running & Athletics',
    'Camping & Hiking',
    'Cycling & Bikes',
    'Team Sports',
    'Football & Soccer',
    'Basketball',
    'Water Sports',
    'Fishing',
    'Yoga & Pilates',
    'Sportswear & Activewear',
    'Outdoor Gear',
    'Hunting',
    'Other',
  ],
  Automotive: [
    'Cars',
    'Motorcycles & Scooters',
    'Bicycles',
    'Buses & Vans',
    'Trucks & Heavy Vehicles',
    'Car Parts & Spares',
    'Engine Parts',
    'Body Parts & Panels',
    'Motorcycle Parts',
    'Bicycle Parts',
    'Tyres & Wheels',
    'Batteries',
    'Oils, Fluids & Lubricants',
    'Filters',
    'Brakes & Suspension',
    'Lighting & Electrical',
    'Interior Accessories',
    'Exterior Accessories',
    'Tools & Diagnostic Equipment',
    'Car Care & Cleaning',
    'Other',
  ],
  'Spare Parts & Components': [
    'Phone Spare Parts',
    'Laptop & PC Spare Parts',
    'TV & Electronics Parts',
    'Appliance Spare Parts',
    'Engine & Mechanical Parts',
    'Electrical Components',
    'Plumbing Parts',
    'Industrial Spare Parts',
    'Machine Parts',
    'Other Spare Parts',
  ],
  Books: [
    'Fiction',
    'Non-Fiction',
    'Educational & Textbooks',
    "Children's Books",
    'Comics & Manga',
    'Religious & Spiritual',
    'Magazines & Periodicals',
    'Reference & Dictionaries',
    'Other',
  ],
  'Office Supplies': [
    'Stationery',
    'Office Furniture',
    'Printers & Scanners',
    'Printing Supplies & Ink',
    'Office Electronics',
    'Filing & Organization',
    'Presentation Supplies',
    'Other',
  ],
  'Toys & Games': [
    'Action Figures',
    'Dolls & Soft Toys',
    'Building Sets & Blocks',
    'Board Games',
    'Puzzles',
    'Educational Toys',
    'Outdoor Play',
    'Video Games',
    'Gaming Accessories',
    'Remote Control Toys',
    'Collectible Toys',
    'Other',
  ],
  'Baby Products': [
    'Strollers & Gear',
    'Car Seats',
    'Feeding & Nursing',
    'Diapers & Wipes',
    'Baby Clothing',
    'Nursery Furniture',
    'Baby Toys',
    'Safety & Monitors',
    'Bath & Skincare',
    'Other',
  ],
  'Pet Supplies': [
    'Dogs — Food',
    'Dogs — Accessories',
    'Dogs — Health & Grooming',
    'Cats — Food',
    'Cats — Accessories',
    'Cats — Health & Grooming',
    'Birds',
    'Fish & Aquarium',
    'Small Pets (Rabbits, Hamsters, etc.)',
    'Reptiles',
    'Pet Beds & Housing',
    'Pet Toys',
    'Pet Carriers & Travel',
    'Live Pets',
    'Other',
  ],
  'Jewelry & Watches': [
    'Fine Jewelry',
    'Fashion Jewelry',
    'Gold & Precious Metals',
    'Watches',
    'Smart Watches',
    'Watch Accessories & Straps',
    'Jewelry Storage',
    'Other',
  ],
  'Musical Instruments': [
    'Guitars & Bass',
    'Keyboards & Pianos',
    'Drums & Percussion',
    'Wind Instruments',
    'String Instruments',
    'DJ & Music Production',
    'Studio Equipment',
    'Instrument Accessories',
    'Other',
  ],
  'Art & Crafts': [
    'Art Supplies',
    'Paint & Canvas',
    'Craft Materials',
    'Finished Artwork',
    'Sewing & Fabric',
    'Yarn & Knitting',
    'Scrapbooking',
    'DIY Kits',
    'Other',
  ],
  'Industrial & Scientific': [
    'Hand Tools',
    'Power Tools',
    'Machinery',
    'Safety Equipment & PPE',
    'Lab & Scientific Equipment',
    'Measuring & Testing Tools',
    'Workwear & Uniforms',
    'Material Handling',
    'Other',
  ],
  Agriculture: [
    'Seeds & Seedlings',
    'Fertilizers & Soil',
    'Pesticides & Crop Protection',
    'Farm Hand Tools',
    'Irrigation & Watering',
    'Livestock Supplies',
    'Animal Feed',
    'Farm Equipment & Machinery',
    'Greenhouse & Nursery',
    'Other',
  ],
  'Building Materials': [
    'Hardware & Fasteners',
    'Cement & Aggregates',
    'Timber, Boards & Plywood',
    'Paints, Finishes & Coatings',
    'Plumbing Materials',
    'Electrical Materials',
    'Roofing Materials',
    'Tiles & Flooring',
    'Doors & Windows',
    'Insulation',
    'Other',
  ],
  Collectibles: [
    'Memorabilia',
    'Trading Cards',
    'Coins & Currency',
    'Stamps',
    'Antiques',
    'Figurines & Models',
    'Sports Collectibles',
    'Other',
  ],
  'Luxury Goods': [
    'Designer Fashion',
    'Designer Accessories',
    'Luxury Watches',
    'Luxury Bags',
    'Luxury Jewelry',
    'Other',
  ],
  'Tools & Hardware': [
    'Hand Tools',
    'Power Tools',
    'Tool Storage',
    'Fasteners & Fixings',
    'Measuring Tools',
    'Welding & Soldering',
    'Garden Tools',
    'Other',
  ],
  'Garden & Outdoor': [
    'Plants & Flowers',
    'Garden Tools',
    'Outdoor Furniture',
    'BBQs & Outdoor Cooking',
    'Garden Decor',
    'Lawn Care',
    'Pots & Planters',
    'Other',
  ],
  'Event & Party': [
    'Party Supplies',
    'Decorations',
    'Costumes',
    'Invitations & Stationery',
    'Tableware (Disposable)',
    'Other',
  ],
  Services: [
    'Professional Services',
    'Home Services (Repair, Cleaning)',
    'Beauty & Personal Services',
    'Education & Tutoring',
    'Events & Catering',
    'Transport & Logistics',
    'IT & Tech Support',
    'Creative Services',
    'Other Services',
  ],
  'Digital Products': [
    'Software & Licenses',
    'E-books',
    'Online Courses',
    'Templates & Graphics',
    'Gift Cards & Vouchers',
    'Domain & Hosting',
    'Digital Art & NFTs',
    'Other',
  ],
  'Real Estate': [
    'Residential for Sale',
    'Residential for Rent',
    'Commercial for Sale',
    'Commercial for Rent',
    'Land & Plots',
    'Short Stay & Airbnb-style',
    'New Developments',
    'Other',
  ],
  'Food & Restaurants': [
    'Prepared Meals',
    'Bakery & Pastry',
    'Catering',
    'Street Food & Snacks',
    'Beverages (Ready)',
    'Other',
  ],
  'Wholesale & Bulk': [
    'Bulk Food & Groceries',
    'Bulk Electronics',
    'Bulk Fashion',
    'Bulk Building Materials',
    'Other Bulk',
  ],
  Others: [
    'General',
    'Uncategorized',
    'Miscellaneous',
    'Custom / Made to Order',
  ],
}

export const CATEGORY_LIST = Object.keys(PRODUCT_CATEGORIES)

export const PLAN_IMAGE_LIMITS: Record<string, number> = {
  free: 6,
  pro: 12,
  business: 20,
}

export const PLAN_FEES: Record<string, number> = {
  free: 8,
  pro: 5,
  business: 3,
}